[versions]
# App & Library Versions
versionCode = "133"
versionName = "1.4.0-beta01"

# SDK Versions
compileSdk = "37"
buildTools = "37.0.0"
minSdk = "23"
targetSdk = "37"

# Dependencies
coreKtx = "1.18.0"
appcompat = "1.7.1"
material = "1.13.0"
constraintlayout = "2.2.1"
browser = "1.10.0"
swiperefreshlayout = "1.2.0"

# Jetpack Extras
biometric = "1.1.0"
lifecycle = "2.10.0"

# Plugins
agp = "9.2.1"
kotlin = "2.3.21"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
